server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectdb
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update